name: sarwat
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  flutter_launcher_icons: ^0.7.4
  
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon" 
  ios: true
  image_path: "image/2.PNG"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    # - image/d.PNG
    - image/1.PNG
    - image/86860268_10163283902630077_7233287206402523136_o.jpg
    - image/3.PNG
    - image/4.PNG
    - image/5.PNG
    - image/6.jpg
    - image/7.jpg
    - image/8.jpg
    - image/9.jpg
    - image/10.jpg
    - image/11.jpg
    - image/12.jpg
    - image/13.jpg
    - image/14.jpg
    - image/15.PNG
    - image/16.PNG
    - image/17.PNG
    - image/18.PNG
    - image/19.PNG
    - image/20.PNG
    - image/21.PNG
    - image/22.PNG
    - image/23.PNG
    - image/25.jpg
    - image/Bigmac.PNG
    - image/Beefburger.PNG
    - image/Big-tasty-Beef.PNG
    - image/Cheese-Burger-Delux.PNG
    - image/CheeseBurger.PNG
    - image/Double-Beefburger.PNG
    - image/Double-Big-Tasty.PNG
    - image/Double-CheeseBurger.PNG
    - image/Double-McRoyal.PNG
    - image/Double-Quarter-pounder.PNG                    
    - image/Little-tasty.PNG
    - image/McDouble.PNG
    - image/McRoyal.PNG
    - image/Quarter-Pounder.PNG
    - image/111.jpg
    - image/222.jpg
    - image/55.jpg
    # - image/Bigmac.PNG
    # - image/Bigmac.PNG

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
